'use strict'

const JOB_STATUS = Object.freeze({
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  RETRY_PENDING: 'RETRY_PENDING',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  DEAD_LETTER: 'DEAD_LETTER'
})

const SOURCES = Object.freeze({
  HUBSPOT: 'hubspot'
})

const ENTITIES = Object.freeze({
  DEAL: 'deal'
})

const JOB_KIND = Object.freeze({
  DEAL: 'deal',
  QUOTE: 'quote'
})

const DEAL_STAGE_CLOSED_WON_ID = '1409249445'

const DEAL_PIPELINE_COMMERCIAL_VISUAL_BRANDING = 't_5728252902aef7e9938dfcbb6cdc2af8'

module.exports = {
  JOB_STATUS,
  SOURCES,
  ENTITIES,
  JOB_KIND,
  DEAL_STAGE_CLOSED_WON_ID,
  DEAL_PIPELINE_COMMERCIAL_VISUAL_BRANDING
}
